language: python
sudo: false
dist: bionic
python:
    - "3.6"
    - "3.7"
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
addons:
  apt:
    packages:
     - zip
     - curl
     - pandoc
     - poppler-utils
install:
    - pip install -r requirements.txt
    - python setup.py install
script:  bash tests/test.sh
